CREATE TABLE IF NOT EXISTS "migrations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "migration" VARCHAR NOT NULL,
  "batch" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "clientes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "nombre" TEXT NOT NULL,
  "apellido" TEXT NOT NULL,
  "correo" VARCHAR NOT NULL,
  "telefono" VARCHAR NOT NULL
);
